requires 'perl' => '5.020';
requires 'lib::relative';
requires 'version';
requires 'CPAN::DistnameInfo';
requires 'Cpanel::JSON::XS' => '4.09';
requires 'IO::Socket::SSL' => '1.56';
requires 'HTTP::Simple';
requires 'MetaCPAN::Client';
requires 'Module::CoreList' => '2.99';
requires 'Mojolicious' => '8.0';
requires 'Mojo::Redis';
requires 'Syntax::Keyword::Try';
requires 'Time::Piece';
requires 'Time::Seconds';
recommends 'Protocol::Redis::XS' => '0.06';
