=head1 NAME

CPAN Dependencies Graph

=head1 SETUP

To run this in a local environment, you need to create a
F<cpan_deps_graph.conf>, for example:

  {
    redis_url => 'redis://localhost/',
  }

Install the dependencies from the F<cpanfile>:

  $ cpanm --installdeps .

Then load the cache with at least one module's data:

  $ perl cpan_deps_graph.pl cache --deeply GraphViz2

Then start the L<application server|Mojolicious::Guides::Cookbook/DEPLOYMENT>:

  $ ./cpan_deps_graph.pl daemon

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2019 by Dan Book.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

Bundled Perl 5 Raptor Copyright (c) 2012, Sebastian Riedel.

Licensed under the CC-SA License, Version 4.0
L<http://creativecommons.org/licenses/by-sa/4.0>.
